### ISSUE TITLE
 readStringPool fun has some bug

### ISSUE THREAD

**Issue by GangWang** [shogo82148/androidbinary#1]
readStringPool fun has some bug

for i, start := range stringStarts {
        var str string
        var err error
        sr.Seek(int64(sp.Header.StringStart+start), os.SEEK_SET)
        if (sp.Header.Flags & UTF8_FLAG) == 0 {
            fmt.Println("---- UTF16 ----")
            str, err = readUTF16(sr)
        } else {
            str, err = readUTF8(sr)

```
        fmt.Println("---- UTF8 ---- :", str)
    }
    if err != nil {
        return nil, err
    }
    sp.Strings[i] = str
}
```

and 
readUTF8 fun
fmt.Println("size:", size)
buf := make([]uint8, size)

---

printf:

size: 12
---- UTF8 ---- : error_layou        // lost "t"
size: 12
---- UTF8 ---- : warning_ico       // lost "n"

**Comment by shogo82148** [comment]
I think that this bug has already been fixed.
Please feel free reopen it if you find some other bugs.
