### ISSUE TITLE
can not get icon. image: unknown format, File "" not found

### ISSUE THREAD

**Issue by di3663** [shogo82148/androidbinary#18]
err says icon file not found or error image format

for example:
```
com.nokia.z
File "" not found

com.google.android.apps.nbu.files
File "%!s(uint32=2131689475)" not found

com.sonyericsson.music
image: unknown format, this error is common in 5% of apks.
```

**Comment by codeskyblue** [comment]
What is your testing code?

**Comment by codeskyblue** [comment]
?? ping @di3663

**Comment by bourne-3** [comment]
> err says icon file not found or error image format
> 
> for example:
> 
> ```
> com.nokia.z
> File "" not found
> 
> com.google.android.apps.nbu.files
> File "%!s(uint32=2131689475)" not found
> 
> com.sonyericsson.music
> image: unknown format, this error is common in 5% of apks.
> ```

i have some problem；panic: image: unknown format
are you had solve the problem？
My requirement is to extract the icon file from the apk file

```
apkPath := "/Users/selwyn/Desktop/taptap_2.68.4-mkt.100000_sem.apk"

	pkg, err := apk.OpenFile(apkPath)
	if err != nil {
		panic(err)
	}
	defer pkg.Close()

	icon, err := pkg.Icon(nil) // returns the icon of APK as image.Image
	if err != nil {
		panic(err)
	}
	fmt.Println(icon)
```
