### ISSUE TITLE
How to range a TableFile?

### ISSUE THREAD

**Issue by hellodword** [shogo82148/androidbinary#23]
Thank you for this amazing lib. I'm using it for apk analyzing in Go. 

How can I range the ```*TableFile``` after ```NewTableFile()``` a ```resources.arsc``` ?

For example, I want to get all strings in ```string.xml```, but do not know the exact ```ResID```.

**Comment by shogo82148** [comment]
There is no range method now.

**Comment by hellodword** [comment]
thx
