### ISSUE TITLE
Add NewAPK api

### ISSUE THREAD

**Issue by codeskyblue** [shogo82148/androidbinary#3]
I want to make a pr for your library.

This pr contains some func.

```go
apk := NewAPK("some.apk")
apk.Icon() # return image.Image
apk.PackageName() # return string of package name
apk.MainActivity() # return acitivty which is necessary to launch app with adb shell am start -n
```

Any suggestions?

**Comment by shogo82148** [comment]
A pr is always welcome!

- Create a new sub-package such as `androidbinary/apk`, and implement functions in it
  - The `androidbinary` package provides only low level API
- Icons vary depending on the target device
  - So the signature of Icon func should be `func Icon(config *android.ResTableConfig) (image.Image, error)`
- Please don't forget error handling

Thank you!

**Comment by codeskyblue** [comment]
Ok I will try to do it.
