### ISSUE TITLE
is there any way i can get uses-permissions?

### ISSUE THREAD

**Issue by Treagzhao** [shogo82148/androidbinary#38]
hi，thx for your package.It`s really helpful , but i still have a problem,is there any way i can get uses-permissions of an apk file？

**Comment by shogo82148** [comment]
You can get the permissions from `Application.Permission`.
https://github.com/shogo82148/androidbinary/blob/c5189dc5c59d9d423308e0475d7d72fa2f1687b9/apk/apkxml.go#L71

If it doesn't work, please send me your apk or android manifest.

**Comment by Treagzhao** [comment]
> You can get the permissions from `Application.Permission`.
> https://github.com/shogo82148/androidbinary/blob/c5189dc5c59d9d423308e0475d7d72fa2f1687b9/apk/apkxml.go#L71
> 
> If it doesn't work, please send me your apk or android manifest.

thx for your reply,but what i need is 'uses-permission'，and i already fork your repository and find a way out ,thank you

**Comment by tonywang** [comment]
Hi @shogo82148 , I create a pull request #46 for support the [uses-permission](https://developer.android.com/guide/topics/manifest/uses-permission-element). If you have time, please help me review it. Hope it could be merged.

**Comment by shogo82148** [comment]
closed by #46 
thanks @tonywang !
